### PR TITLE
New Page Scroll plugin

### PR DESCRIPTION
**Pull request by aparajita**
And used my full name in my previous plugins.

### CODE REVIEW

**Comment by mikob** [comment]
Actually I was going to change the existing scroll up/down command to scroll based on the window height in the main browser plugin. Can you uninclude the page scroll plugin and I'll accept your other changes for the author name, version updates.

**Comment by aparajita** [comment]
I'll make a new PR. Feel free to use my code for the scrolling. You don't want to scroll 100% of the viewport height, because a lot of sites have fixed headers.

**Comment by mikob** [comment]
Included the new scrolling by ratio of window.height as well as left/right scrolling in v1.2. Hope you saw your attribution in the update credits!

**Comment by aparajita** [comment]
I did, thank you. 😁

**Pull request closed without merging**
